name: Build Work_test Module

on:
  workflow_dispatch:
  release:
    types: [released]
  push:
    branches:
      - master
    paths:
      - '**/tutorials/github.com/alice52/work_test/**'
      - '.github/workflows/build-worktest.yml'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] # "macOS-latest"
        go: ['1.18.x', '1.19.x', '1.20.x', '1.21.x']
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      PROJECT_PREFIX: tutorials/github.com/alice52/work_test
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build Work_test Module
        run: |
          cd $PROJECT_HOME/$PROJECT_PREFIX
          go list -f '{{.Dir}}/...' -m | xargs go build -o bin/
          ls -la
          cd bin/
          ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.go }}-Artifact
          path: ${{ github.workspace }}/**/bin/*
          retention-days: 7
