name: Build Oss Proxy Serverless Func

on:
  workflow_dispatch:
  release:
    types: [released]
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env: # define constant
      PROJECT_PREFIX: tutorials/io.github.alice52.proxy
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Oss Proxy Serverless Func
        run: |
          PROJECT_NAME=oss
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME
          go build -o main
          zip main.zip main

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.zip
          path: ${{ github.workspace }}/**/main.zip
          retention-days: 7
